on: push
jobs:
  lint:
    uses: internetarchive/dyno/.github/workflows/lint.yml@main

  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      NOMAD_VAR_HOSTNAMES: '["jpg241.dev.archive.org"]'
