on: push
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      NOMAD_VAR_HOSTNAMES: '["jpg241.dev.archive.org","jpg241.archive.org"]'
